export const languages: Record<string, string> = {
    "Assamese": "asm_Beng",
    "Kashmiri": "kas_Arab",
    "Punjabi" : "pan_Guru",
    "Bengali" : "ben_Beng",
    "Kashmiri (Devanagari)": "kas_Deva",
    "Sanskrit" : "san_Deva",
    "Bodo" : "brx_Deva",
    "Maithili": "mai_Deva",
    "Santali": "sat_Olck",
    "Dogri" : "doi_Deva",
    "Malayalam" : "mal_Mlym",
    "Sindhi (Arabic)" : "snd_Arab",
    "English" : "eng_Latn",
    "Marathi": "mar_Deva",
    "Sindhi (Devanagari)": "snd_Deva",
    "Konkani": "gom_Deva",
    "Manipuri (Bengali)": "mni_Beng",
    "Tamil": "tam_Taml",
    "Gujarati": "guj_Gujr",
    "Manipuri (Meitei)": "mni_Mtei",
    "Telugu" : "tel_Telu",
    "Hindi" : "hin_Deva",
    "Nepali" : "npi_Deva",
    "Urdu" : "urd_Arab",
    "Kannada": "kan_Knda",
    "Odia": "ory_Orya"
}